import { createGlobalTheme } from "@vanilla-extract/css";

export const vars = createGlobalTheme(":root", {
  color: {
    primary: "#1a1a2e",
    primaryHover: "#2d2d44",
    secondary: "#f5f5f7",
    secondaryHover: "#e8e8eb",
    background: "#f8f9fa",
    surface: "#ffffff",
    border: "#e5e7eb",
    borderDashed: "#d1d5db",
    textPrimary: "#1f2937",
    textSecondary: "#6b7280",
    textMuted: "#9ca3af",
    error: "#dc2626",
    errorBg: "#fef2f2",
    success: "#047857",
    successBg: "#d1fae5",
    successLight: "#f0fdf4",
    successBorder: "#bbf7d0",
  },
  space: {
    xs: "4px",
    sm: "8px",
    md: "12px",
    lg: "16px",
    xl: "24px",
    "2xl": "32px",
    "3xl": "48px",
  },
  radius: {
    sm: "4px",
    md: "6px",
    lg: "8px",
    xl: "12px",
    full: "9999px",
  },
  fontSize: {
    xs: "12px",
    sm: "13px",
    base: "14px",
    md: "15px",
    lg: "16px",
    xl: "18px",
    "2xl": "24px",
    "3xl": "28px",
    "4xl": "32px",
  },
  fontWeight: {
    normal: "400",
    medium: "500",
    semibold: "600",
  },
});
